# Generated by Django 4.2.6 on 2023-10-30 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contry_code',
            new_name='country_code',
        ),
    ]
